name: Go Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc clang libc6-dev libgl1-mesa-dev xorg-dev

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Go Build
        run: go build -o bin/go-games .

      - name: Go Test
        run: go test -v ./...

      - name: Go Vet
        run: go vet -v ./...

      - name: Go FMT
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-path: ./
          gofmt-flags: '-l -d'

      - name: Go Staticcheck
        uses: dominikh/staticcheck-action@v1.3.1
        with:
          install-go: false
          cache-key: 1.24
          working-directory: ./
