name: Go Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: branch
        run: |
          if [[ ${{ github.ref }} == 'refs/heads'* ]]; then # This is a branch, not a pull request
            echo "branch=$(echo ${{ github.ref }} | sed -E 's|refs/[a-zA-Z]+/||')" >> $GITHUB_OUTPUT
          else
            echo "branch=$(echo ${{ github.head_ref }} | sed -E 's|refs/[a-zA-Z]+/||')" >> $GITHUB_OUTPUT
          fi

      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.branch.outputs.branch }}

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Go Build
        run: GOOS=darwin GOARCH=arm64 go build -o bin/go-games .

      - name: Go Test
        run: go test -v ./...

      - name: Go Vet
        run: go vet -v ./...

      - name: Go FMT
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-path: ./
          gofmt-flags: '-l -d'

      - name: Go Staticcheck
        uses: dominikh/staticcheck-action@v1.3.1
        with:
          install-go: false
          cache-key: 1.24
          working-directory: ./
