name: Go Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Go Test
        run: go test -v ./...

      - name: Go Vet
        run: go vet -v ./...

      - name: Go FMT
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-path: ./
          gofmt-flags: '-l -d'

      - name: Go Staticcheck
        uses: dominikh/staticcheck-action@v1.3.1
        with:
          install-go: false
          cache-key: 1.24
          working-directory: ./

  build-macos-arm64:
    runs-on: macos-latest
    needs: test
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Build for macOS arm64
        run: GOOS=darwin GOARCH=arm64 go build -o bin/go-games .
